### ISSUE TITLE
Thanks, cant add more buttons why?

### ISSUE THREAD

**Issue by PIBSAS** [colormono/retropie-joystick#1]
Your code works graet with 6 buttons select + start, but cant add more buttons, why?

**Comment by colormono** [comment]
Hi @Luciano2018, glad you like it. In order to make this code work for a larger amount of buttons, you should: 
1) Pass amount of buttons as the third argument of Joystick_ Joystick(1, 2, HERE, ...). _(line 14)_
2) Initialize Button Pins on the setup() functions. _(line 31)_
3) Add some space for them in lastButtonState. _(line 45)_
4) Handle setButton case inside the switch statement. _(line 65)_

Let me know if this approach works for you, or if there is anything I can help with.
Best.

**Comment by PIBSAS** [comment]
Thanks i mess up with 3 and 4 step 😋, i knew that was impossible cant add more buttons, thanks again for share this code and help me!
